# Generated by Django 2.2.6 on 2019-10-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='pbi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Pbi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Productowner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Productbacklog'),
        ),
    ]
