# Generated by Django 2.2.1 on 2019-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='status',
            field=models.CharField(choices=[('INP', 'in progress'), ('FN', 'finished'), ('NO', 'not started')], default='NO', max_length=20),
        ),
    ]
