# Generated by Django 2.2.1 on 2019-11-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0002_sprintbacklog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbacklog',
            name='remaining_story_points',
        ),
        migrations.RemoveField(
            model_name='productbacklog',
            name='total_number_of_pbi',
        ),
        migrations.RemoveField(
            model_name='productbacklog',
            name='total_story_points',
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='remaining_hours',
        ),
    ]
